apiVersion: apps/v1
kind: Deployment
metadata:
  name: yabtaour-app
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yabtaour-app
  template:
    metadata:
      labels:
        app: yabtaour-app
    spec:
      containers:
      - name: app
        image: darkhamid/pt3:v1
        ports:
        - containerPort: 80
